// Retstekster til kunde-onboarding (DA/EN). Delt kilde mellem formular og signeret PDF.
// De fulde/endelige tekster skal godkendes af jurist — jf. Onboarding-Retstekster-UDKAST.

export type Lang = 'da' | 'en'

export const LEGAL: Record<Lang, { terms: string; gdpr: string; ls: string; guar: string }> = {
  da: {
    terms: `<h4>1. Anvendelse</h4><p>Betingelserne gælder alle leverancer fra Venmark Fisk A/S til erhvervskunder.</p><h4>2. Priser</h4><p>Fisk handles som dagsvarer; priser — særligt auktionsvarer — kan ændre sig frem til leveringsdagen. Ønskes fast maks.pris, angives det i bemærkning.</p><h4>3. Betaling</h4><p>Betalingsbetingelser er løbende uge + 5 dage. Ved forsinkelse påløber rente efter renteloven.</p><h4>4. Reklamation</h4><p>Da der er tale om letfordærvelige fødevarer, skal reklamation ske straks ved modtagelsen og senest inden 24 timer.</p><h4>5. Ansvar & værneting</h4><p>Venmark er ikke ansvarlig for indirekte tab. Tvist afgøres efter dansk ret ved kundens retskreds.</p>`,
    gdpr: `<h4>Dataansvarlig</h4><p>Venmark Fisk A/S, CVR 33050151, Søndergade 50, 9850 Hirtshals.</p><h4>Formål & retsgrundlag</h4><p>Oprettelse og administration af kundeforholdet (aftale), bogføring (lovkrav), kreditvurdering (legitim interesse) og markedsføring (samtykke).</p><h4>Opbevaring</h4><p>Så længe kundeforholdet består + op til 5 år (bogføringsloven).</p><h4>Rettigheder</h4><p>Indsigt, berigtigelse, sletning m.m. Kontakt fisk@venmark.dk. Klage til Datatilsynet.</p>`,
    ls: `<p>Virksomheden tilmelder betaling af skyldige beløb til Venmark Fisk A/S (CVR 33050151) via Leverandørservice og bemyndiger Venmark til gennem Mastercard Payment Services (Nets) at hæve forfaldne beløb på den anførte konto.</p><p>Tilmeldingen gælder løbende, indtil den skriftligt opsiges. Opkrævninger varsles efter Leverandørservices regler, og betaleren kan gøre indsigelse inden for gældende frister.</p>`,
    guar: `<p>Kautionisten påtager sig som <b>selvskyldnerkautionist</b> at hæfte personligt og solidarisk for ethvert krav mod virksomheden — <b>ubegrænset, til den til enhver tid værende saldo</b>, inkl. hovedstol, renter, gebyrer og omkostninger.</p><p>Venmark kan søge sig fyldestgjort direkte hos kautionisten, når kravet er forfaldent, uden først at søge virksomheden. Kautionen er fortløbende, indtil den skriftligt opsiges for fremtidig gæld.</p>`,
  },
  en: {
    terms: `<h4>1. Application</h4><p>These terms apply to all deliveries from Venmark Fisk A/S to business customers.</p><h4>2. Prices</h4><p>Fish is traded as daily goods; prices — auction goods in particular — may change up to the day of delivery. A fixed maximum price must be stated in the order remarks.</p><h4>3. Payment</h4><p>Payment terms are current week plus 5 days. Late payment incurs interest under the Danish Interest Act.</p><h4>4. Complaints</h4><p>As the goods are perishable, complaints must be made immediately upon receipt and no later than 24 hours.</p><h4>5. Liability & venue</h4><p>Venmark is not liable for indirect losses. Disputes are settled under Danish law in the customer's jurisdiction.</p>`,
    gdpr: `<h4>Data controller</h4><p>Venmark Fisk A/S, reg. no. 33050151, Søndergade 50, 9850 Hirtshals, Denmark.</p><h4>Purposes & legal basis</h4><p>Setup and administration of the customer relationship (contract), accounting (legal obligation), credit assessment (legitimate interest) and marketing (consent).</p><h4>Retention</h4><p>For the duration of the relationship + up to 5 years (accounting law).</p><h4>Rights</h4><p>Access, rectification, erasure etc. Contact fisk@venmark.dk. Complaints to the Danish DPA.</p>`,
    ls: `<p>The company registers payment of amounts due to Venmark Fisk A/S (reg. no. 33050151) via Leverandørservice and authorises Venmark, through Mastercard Payment Services (Nets), to collect amounts due from the stated account.</p><p>The registration is ongoing until terminated in writing. Collections are notified under the Leverandørservice rules, and the payer may object within the applicable deadlines.</p>`,
    guar: `<p>The guarantor undertakes, as a <b>guarantor on a primary-obligor basis</b>, to be personally and jointly liable for any claim against the company — <b>unlimited, up to the outstanding balance from time to time</b>, incl. principal, interest, fees and costs.</p><p>Venmark may seek satisfaction directly from the guarantor once the claim falls due, without first pursuing the company. The guarantee is continuing until terminated in writing for future debt.</p>`,
  },
}

export const TERMS_VERSION = '2026-09'
